import type { DashboardDataset } from "./types";

export const dashboardDataset: DashboardDataset = {
  metrics: [
    {
      id: "quality",
      label: "出力品質",
      value: 92.4,
      target: 90,
      unit: "%",
      direction: "higher-is-better",
    },
    {
      id: "safety",
      label: "安全性",
      value: 98.1,
      target: 99,
      unit: "%",
      direction: "higher-is-better",
    },
    {
      id: "latency",
      label: "遅延",
      value: 1240,
      target: 1500,
      unit: "ms",
      direction: "lower-is-better",
    },
    {
      id: "cost",
      label: "平均コスト",
      value: 0.018,
      target: 0.025,
      unit: "USD",
      direction: "lower-is-better",
    },
  ],
  runs: [
    {
      id: "run_1042",
      agentName: "Support Triage Agent",
      scenario: "問い合わせ分類と返信草案",
      model: "gpt-5-mini",
      promptVersion: "prompt-v18",
      status: "passed",
      startedAt: "2026-07-01T08:40:00+09:00",
      durationMs: 1184,
      costUsd: 0.016,
      qualityScore: 94.2,
      safetyScore: 99.1,
      latencyMs: 1184,
      summary: "分類精度と禁止表現回避が基準を上回りました。",
    },
    {
      id: "run_1041",
      agentName: "Release Note Agent",
      scenario: "PR差分からリリースノート生成",
      model: "gpt-5",
      promptVersion: "prompt-v12",
      status: "warning",
      startedAt: "2026-07-01T08:18:00+09:00",
      durationMs: 1460,
      costUsd: 0.023,
      qualityScore: 91.7,
      safetyScore: 98.4,
      latencyMs: 1460,
      summary: "品質は合格。安全性チェックで1件の要確認項目があります。",
    },
    {
      id: "run_1040",
      agentName: "Incident Summary Agent",
      scenario: "障害ログ要約",
      model: "gpt-5-mini",
      promptVersion: "prompt-v17",
      status: "failed",
      startedAt: "2026-07-01T07:54:00+09:00",
      durationMs: 1730,
      costUsd: 0.021,
      qualityScore: 84.9,
      safetyScore: 96.8,
      latencyMs: 1730,
      summary: "根拠引用の欠落により品質ゲートを通過しませんでした。",
    },
    {
      id: "run_1039",
      agentName: "Policy Review Agent",
      scenario: "社内規約の変更影響レビュー",
      model: "gpt-5",
      promptVersion: "prompt-v18",
      status: "running",
      startedAt: "2026-07-01T08:52:00+09:00",
      durationMs: 640,
      costUsd: 0.012,
      qualityScore: 89.6,
      safetyScore: 98.7,
      latencyMs: 640,
      summary: "評価セットを実行中です。",
    },
  ],
  findings: [
    {
      id: "sec_31",
      title: "PIIに近い入力をそのまま引用する可能性",
      severity: "high",
      status: "triaged",
      owner: "security-review",
      relatedRunId: "run_1041",
    },
    {
      id: "sec_30",
      title: "根拠URLがない回答を確信表現で返す",
      severity: "medium",
      status: "open",
      owner: "eval-team",
      relatedRunId: "run_1040",
    },
    {
      id: "sec_29",
      title: "禁止語彙フィルタの誤検知",
      severity: "low",
      status: "resolved",
      owner: "platform",
      relatedRunId: "run_1038",
    },
  ],
  promptVersions: [
    {
      id: "prompt-v18",
      name: "根拠優先・短文回答ポリシー",
      status: "candidate",
      author: "Roga",
      changedAt: "2026-07-01T07:30:00+09:00",
      qualityDelta: 3.4,
      safetyDelta: 0.8,
      note: "引用欠落時は回答を保留する条件を追加。",
    },
    {
      id: "prompt-v17",
      name: "障害ログ要約テンプレート",
      status: "stable",
      author: "platform",
      changedAt: "2026-06-30T18:20:00+09:00",
      qualityDelta: -1.2,
      safetyDelta: 0.2,
      note: "ログ断片の優先順位を調整。",
    },
    {
      id: "prompt-v12",
      name: "リリースノート生成",
      status: "stable",
      author: "devex",
      changedAt: "2026-06-28T14:10:00+09:00",
      qualityDelta: 1.8,
      safetyDelta: -0.4,
      note: "breaking change の検出条件を追加。",
    },
  ],
  releaseGates: [
    {
      id: "unit",
      label: "単体テスト",
      status: "passed",
      evidence: "128件成功",
    },
    {
      id: "eval",
      label: "評価セット",
      status: "warning",
      evidence: "1シナリオ再評価中",
    },
    {
      id: "security",
      label: "安全性",
      status: "warning",
      evidence: "High 1件 triaged",
    },
    {
      id: "deploy",
      label: "デプロイ判定",
      status: "warning",
      evidence: "手動承認待ち",
    },
  ],
  activities: [
    {
      id: "act_1",
      happenedAt: "08:52",
      actor: "Policy Review Agent",
      action: "評価セットを開始しました",
      tone: "neutral",
    },
    {
      id: "act_2",
      happenedAt: "08:40",
      actor: "Support Triage Agent",
      action: "全ゲートに合格しました",
      tone: "success",
    },
    {
      id: "act_3",
      happenedAt: "08:18",
      actor: "Security Review",
      action: "High finding を triage 済みにしました",
      tone: "warning",
    },
    {
      id: "act_4",
      happenedAt: "07:54",
      actor: "Incident Summary Agent",
      action: "品質ゲートで停止しました",
      tone: "danger",
    },
  ],
};
